-- ============================================================================
-- PR purchasing work-summary: assignment + free-text remark per PR document
-- ใช้โดยหน้า "สรุปงาน PR จัดซื้อ" (PrPurchaseSummaryView.vue)
-- รันบน Supabase (SQL Editor)
-- ----------------------------------------------------------------------------
-- pr_key   = เลขที่เอกสาร PR (document_number) — ตัวตนของใบ PR ใช้กันซ้ำ/upsert
-- assignee = ชื่อผู้จัดซื้อที่ถูกมอบหมาย (system_users.fullname)
-- remark   = โน้ตอิสระว่าติดอะไรบ้าง (เขียนเอง)
-- ============================================================================

create table if not exists public.pr_purchase_tracking (
  id          bigint generated by default as identity primary key,
  pr_key      text not null,
  assignee    text,
  remark      text,
  updated_by  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- กันซ้ำระดับฐานข้อมูล → ให้ upsert(onConflict: pr_key) ทำงานได้
create unique index if not exists pr_purchase_tracking_pr_key_uniq
  on public.pr_purchase_tracking (pr_key);
