-- ============================================================================
-- รายชื่อผู้จัดซื้อ (สำหรับ dropdown "มอบหมาย" + แผงข้างหน้า "สรุปงาน PR จัดซื้อ")
-- ใช้โดย PrPurchaseSummaryView.vue
-- รันบน Supabase (SQL Editor)
-- ----------------------------------------------------------------------------
-- เดิมรายชื่อ 6 คนถูก hardcode ไว้ในไฟล์ .vue → เพิ่มคนใหม่ต้องแก้โค้ด+deploy
-- ย้ายมาเก็บในตารางนี้เพื่อให้เพิ่ม/แก้ผ่านหน้าเว็บได้ และแชร์ให้ทุก user เห็นตรงกัน
--
-- code = รหัสพนักงาน (L2304126 ฯลฯ) — ตัวตนใช้กันซ้ำ
-- name = ชื่อ-นามสกุล ต้องตรงกับค่าที่บันทึกใน pr_purchase_tracking.assignee
--        (การนับ "มอบหมายแล้ว" จับคู่ด้วยชื่อ ไม่ใช่รหัส)
-- ============================================================================

create table if not exists public.pr_purchasers (
  id          bigint generated by default as identity primary key,
  code        text not null,
  name        text not null,
  active      boolean not null default true,
  created_by  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create unique index if not exists pr_purchasers_code_uniq on public.pr_purchasers (code);

-- ----------------------------------------------------------------------------
-- ข้อมูลตั้งต้น: 6 รายชื่อเดิมที่เคย hardcode ไว้ในโค้ด
-- (on conflict do nothing → รันซ้ำได้ ไม่ทับของที่แก้ไปแล้ว)
-- ----------------------------------------------------------------------------
insert into public.pr_purchasers (code, name) values
  ('L2304126',  'สินทะสอน อินทะวง'),
  ('L26022053', 'คำกอง แก้วมะนี'),
  ('L2602022',  'พอนวิไลสัก ฟองสานุวง'),
  ('L2605038',  'เกียงสะไหม ไชยะพูมี'),
  ('L2606013',  'เจียง'),
  ('L2509101',  'ลัดสะหมี ลาดสะบันดิด')
on conflict (code) do nothing;

-- ----------------------------------------------------------------------------
-- สิทธิ์เข้าถึง: แอปยิงผ่าน anon key → ต้อง grant + เปิด policy ให้ anon อ่าน/เขียนได้
-- (ไม่งั้น insert เงียบๆ ล้มเหลว → เพิ่มชื่อแล้วหายตอน reload)
-- ----------------------------------------------------------------------------
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.pr_purchasers to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public.pr_purchasers enable row level security;

drop policy if exists pr_purchasers_all on public.pr_purchasers;
create policy pr_purchasers_all
  on public.pr_purchasers
  for all
  to anon, authenticated
  using (true)
  with check (true);
